package:
  name: picard
  version: "2.2.4"

source:
  fn: picard.jar
  url: https://github.com/broadinstitute/picard/releases/download/2.2.4/picard-tools-2.2.4.zip
  md5: f5ec2c2a1fb5b287a1ec5cae7cd8bef8

build:
  number: 1
  skip: False

requirements:
  run:
    - openjdk >=8
    - python

test:
  commands:
    - "picard 2>&1 | grep USAGE:"

about:
  home: "http://broadinstitute.github.io/picard/"
  license: MIT
  summary: "Java tools for working with NGS data in the BAM format"
