package:
  name: picard
  version: "2.12.2"

source:
  fn: picard.jar
  url: https://github.com/broadinstitute/picard/releases/download/2.12.2/picard.jar
  md5: e28340effacc9b13397954acfdcc3145

build:
  number: 1
  skip: False

requirements:
  run:
    - openjdk >=8
    - python

test:
  commands:
    - "picard 2>&1 | grep USAGE:"

about:
  home: "http://broadinstitute.github.io/picard/"
  license: MIT
  summary: "Java tools for working with NGS data in the BAM format"
