{% set version = "1.5.2" %}

package:
  name: vardict-java
  version: {{ version }}

source:
  git_url: https://github.com/AstraZeneca-NGS/VarDictJava.git
  git_rev: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk
  run:
    - openjdk
    - perl
    - r

test:
  commands:
    - vardict-java -h
    - vardict-strandbias
    - vardict-testsomatic
    - vardict-var2vcf
    - vardict-var2vcf-paired

about:
  home: https://github.com/AstraZeneca-NGS/VarDictJava
  license: MIT
  summary: Java port of the VarDict variant discovery program

extra:
  skip-lints:
    - uses_git_url
    - missing_hash
  notes: >
    Provides five binaries:
    * `vardict-java`
    * `vardict-strandbias`
    * `vardict-testsomatic`
    * `vardict-var2vcf`
    * `vardict-var2vcf-paired`

    A typical single sample variant call would involve
    `vardict-java [some flags] | vardict-strandbias | vardict-var2vcf [some flags]`
    A typical paired variant call would involve
    `vardict-java [some flags] | vardict-testsomatic | vardict-var2vcf-paired [some flags]`
