package:
  name: picard
  version: "2.3.0"

source:
  fn: picard.jar
  url: https://github.com/broadinstitute/picard/releases/download/2.3.0/picard-tools-2.3.0.zip
  md5: 25e2c3a9ab1626fb3ffd700d57024f29

build:
  number: 1
  skip: False

requirements:
  run:
    - openjdk >=8
    - python

test:
  commands:
    - "picard 2>&1 | grep USAGE:"

about:
  home: "http://broadinstitute.github.io/picard/"
  license: MIT
  summary: "Java tools for working with NGS data in the BAM format"
