package:
  name: xs
  version: 1.0.0

source:
  url: https://github.com/pratas/xs/archive/v1.tar.gz
  md5: 9fd0d370bcdc3886858f775ce593d65f

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}

test:
  commands:
    - XS -n 1 /dev/null

about:
  home: https://github.com/pratas/xs
  license: GPL-2.0
  summary: XS is a skilled FASTQ read simulation tool, flexible, portable (does not need a reference sequence) and tunable in terms of sequence complexity
